const teamMembers_3year = [
    {
        id: 1,
        name: "Ankit Yadav",
        position: "ML Lead",
        image: "https://i.ibb.co/DD8Q3h9C/IMG-20231014-213547-2.jpg",
        linkedin: "https://www.linkedin.com/in/ankit-yadav-38a005257/",
        year: 3,
        github: "https://github.com/02ankit482",
    }
    ,
    {
        id: 2,
        name: "Anshita Siroya",
        position: "Co Lead",
        image: "https://i.ibb.co/B2K8Zbkx/IMG-20250225-WA0007.jpg",
        linkedin: "https://www.linkedin.com/in/anshita-siroya-18a9b3256/",
        year: 3,
        github: "https://github.com/anshi0",
    },
    {
        id: 3,
        name: "Anurag",
        position: "Lead",
        image: "",
        linkedin: "https://www.linkedin.com/in/anurag-varshney-6a6a4321b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        year: 3,
        github: "",
    },
    {
        id: 4,
        name: "Anubhav Mishra ",
        position: "Web Team",
        image: "https://i.ibb.co/pjFDdqjk/resized-second-image.jpg",
        linkedin: "https://www.linkedin.com/in/anubhav-mi",
        year: 3,
        github: "https://github.com/Anubhav-MI",
    }, {
        id: 5,
        name: "Anush Saxena ",
        position: "Gang leader",
        image: "https://i.ibb.co/Jwgqm92t/Screenshot-2025-0327-014504.jpg",
        linkedin: "https://www.linkedin.com/in/anush-saxena-582047248",
        year: 3,
        github: "GitHub.com/Anush-Saxena",
    }, {
        id: 6,
        name: "Tanishq Chauhan",
        position: "App Team",
        image: "https://i.ibb.co/YFXnJbfm/Formal-Tanishq-photo.png",
        linkedin: "www.linkedin.com/in/tanishq-chauhan-936b25258",
        year: 3,
        github: "https://github.com/Volcandrabuzz",
    }, {
        id: 7,
        name: "Yatha Grover",
        position: "ML team",
        image: "https://i.ibb.co/JWkFndbv/yatha.jpg",
        linkedin: "https://www.linkedin.com/in/yatha-grover-9a7275253/",
        year: 3,
        github: "https://github.com/YATHAGROVER",
    }, {
        id: 8,
        name: "Abhishek Raj",
        position: "UI/UX Lead",
        image: "https://i.ibb.co/N22b9T4g/profile.jpg",
        linkedin: "https://www.linkedin.com/in/abhishek-raj-a09181215",
        year: 3,
        github: "https://github.com/abhishekrj02",
    }, {
        id: 9,
        name: "Prashant Tripathi",
        position: "App Team",
        image: "https://ibb.co/WNrXH2Q8",
        linkedin: "https://www.linkedin.com/in/prashant-tripathi-7b7b3b1b5",
        year: 3,
        github: "https://github.com/Pt1234567",
    }, {
        id: 10,
        name: "Harshvardhan ",
        position: "App Team",
        image: "https://i.ibb.co/84sg2ck9/4e0229c4-fe1d-4823-996e-750d5ed30f56.jpg",
        linkedin: "",
        year: 1,
        github: "",
    }
]